import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { psiLeaf, psiMerkleRoot, PSI_SCHEMA_ID, PSI_SCHEMA_RULES } from "@/lib/psi-schema";
import { jcsCanonicalize } from "@/lib/psi-canonicalize";
import { sha256Hex } from "@/lib/hello-psi";

// Golden vectors generated by the Python suite (psi-conformance/conformance.py,
// canonicalisation via psi-conformance/psi_jcs.py — true RFC 8785).
// This file is the drift gate: the TypeScript primitives that ship inside the
// browser bundle MUST reproduce the Python digests byte for byte. If this
// suite fails, /conformance cannot claim cross-language parity.

const VEC = resolve(__dirname, "../../psi-conformance/vectors");
const load = <T>(f: string): T => JSON.parse(readFileSync(resolve(VEC, f), "utf8")) as T;

type ShaVec = { input: string; sha256: string };
type CanonVec = { canonical: string; input: unknown };
type LeafVec = { hash: string; leaf: string };
type MerkleVec = { leaves: string[]; root: string };
type NegVec = {
  leaf_differs_on_hash: { correct_leaf: string; wrong_leaf: string };
  merkle_differs_on_reorder: { ab: string; ba: string };
  sha_differs_on_input: { a: string; b: string };
};

describe("PSI-SEAL/1 — vector files are present", () => {
  for (const f of ["sha256.json", "canonicalization.json", "leaf.json", "merkle.json", "negative.json"]) {
    it(`ships psi-conformance/vectors/${f}`, () => {
      expect(existsSync(resolve(VEC, f))).toBe(true);
      expect(readFileSync(resolve(VEC, f), "utf8").trim().length).toBeGreaterThan(0);
    });
  }
});

describe("PSI-SEAL/1 — R5 SHA-256 over the raw octet stream", () => {
  const vectors = load<ShaVec[]>("sha256.json");
  it("has five known answers", () => expect(vectors).toHaveLength(5));
  for (const v of vectors) {
    it(`sha256Hex(${JSON.stringify(v.input).slice(0, 28)}) matches Python`, async () => {
      expect(await sha256Hex(v.input)).toBe(v.sha256);
    });
  }
});

describe("PSI-SEAL/1 — R1 RFC 8785 canonicalisation", () => {
  const vectors = load<CanonVec[]>("canonicalization.json");
  it("has eight known answers", () => expect(vectors).toHaveLength(8));
  for (const v of vectors) {
    it(`jcsCanonicalize matches Python: ${v.canonical.slice(0, 34)}`, () => {
      expect(jcsCanonicalize(v.input)).toBe(v.canonical);
    });
  }
});

describe("PSI-SEAL/1 — R9 domain-separated leaf", () => {
  const vectors = load<LeafVec[]>("leaf.json");
  it("has five known answers", () => expect(vectors).toHaveLength(5));
  for (const v of vectors) {
    it(`psiLeaf(${v.hash.slice(0, 12)}…) matches Python`, async () => {
      expect(await psiLeaf(v.hash)).toBe(v.leaf);
    });
  }
});

describe("PSI-SEAL/1 — R8 Merkle assembly (odd node promoted)", () => {
  const vectors = load<MerkleVec[]>("merkle.json");
  it("has five trees of increasing size", () => expect(vectors.map((v) => v.leaves.length)).toEqual([1, 2, 3, 4, 5]));
  for (const v of vectors) {
    it(`psiMerkleRoot over ${v.leaves.length} leaves matches Python`, async () => {
      expect(await psiMerkleRoot(v.leaves)).toBe(v.root);
    });
  }
});

describe("PSI-SEAL/1 — negative vectors (sensitivity, not acceptance)", () => {
  const neg = load<NegVec>("negative.json");
  const leaves = load<MerkleVec[]>("merkle.json")[1].leaves;

  it("reordered leaves produce a different root (R8 order sensitivity)", async () => {
    expect(await psiMerkleRoot([leaves[0], leaves[1]])).toBe(neg.merkle_differs_on_reorder.ab);
    expect(await psiMerkleRoot([leaves[1], leaves[0]])).toBe(neg.merkle_differs_on_reorder.ba);
  });

  it("a wrong leaf does not verify for the same hash (R9)", async () => {
    const row = load<LeafVec[]>("leaf.json").find((l) => l.leaf === neg.leaf_differs_on_hash.correct_leaf);
    expect(row).toBeDefined();
    const computed = await psiLeaf(row!.hash);
    expect(computed).toBe(neg.leaf_differs_on_hash.correct_leaf);
    expect(computed).not.toBe(neg.leaf_differs_on_hash.wrong_leaf);
  });

  it("different inputs never collide on the digest (R5)", async () => {
    const sha = load<ShaVec[]>("sha256.json");
    const a = sha.find((s) => s.sha256 === neg.sha_differs_on_input.a);
    expect(a).toBeDefined();
    expect(await sha256Hex(a!.input)).toBe(neg.sha_differs_on_input.a);
    expect(neg.sha_differs_on_input.a).not.toBe(neg.sha_differs_on_input.b);
  });
});

describe("PSI-SEAL/1 — the rule set the page displays", () => {
  it("is the twelve-rule R1–R12 canonical set", () => {
    expect(PSI_SCHEMA_ID).toBe("PSI-SEAL/1.0.0");
    expect(PSI_SCHEMA_RULES).toHaveLength(12);
    expect(PSI_SCHEMA_RULES[0]).toContain("R1");
    expect(PSI_SCHEMA_RULES[11]).toContain("R12");
  });
});
